[project]
name = "astron-rpa-engine"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aioimaplib>=2.0.1",
    "anyio>=4.10.0",
    "apscheduler>=3.11.0",
    "exceptiongroup>=1.3.0",
    "fastapi>=0.116.1",
    "idna>=3.10",
    "importlib-metadata>=8.7.0",
    "keyboard>=0.13.5",
    "loguru>=0.7.3",
    "no-config>=0.1.5",
    "opencv-python>=4.12.0.88",
    "pandas>=2.3.2",
    "psutil>=7.0.0",
    "pyautogui>=0.9.54",
    "pyright>=1.1.405",
    "python-lsp-server>=1.13.1",
    "pywin32>=311",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
    "sniffio>=1.3.1",
    "sseclient>=0.0.27",
    "starlette>=0.47.3",
    "toml>=0.10.2",
    "twine>=6.2.0",
    "typing-extensions>=4.15.0",
    "uvicorn>=0.35.0",
    "watchfiles>=1.1.0",
    "websocket-client>=1.8.0",
    "websockets>=15.0.1",
    "importlib_metadata",
    "rpaframe",
    "rpawebsocketclient",
    "rpawebsocket",
    "pythonnet>=3.0.5",
    "uiautomation>=2.0.29",
    "pywinhook>=1.6.2",
    "pynput>=1.8.1",
    "pillow>=11.3.0",
    "black>=25.1.0",
    "isort>=6.0.1",
]

[dependency-groups]

############################################################
# [ Dev ] dependency group
# Required for development and running tests
############################################################
dev = [
  "ruff~=0.12.3"
]


[tool.uv.sources]
rpaframe = { path = "shared/rpaframe" }
rpawebsocket = { path = "shared/rpawebsocket" }
rpawebsocketclient = { path = "shared/rpawebsocket-client" }

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
