name: Style check

on:
  workflow_call:

concurrency:
  group: style-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write
  statuses: write
  contents: read

jobs:
  python-style:
    name: Python Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            engine/**
            .github/workflows/style.yml

      - name: Setup UV and Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: false
          python-version: "3.13"
          cache-dependency-glob: engine/uv.lock

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: uv sync --project engine --dev
      
      - name: Run Ruff check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: uv run --project engine --dev ruff format ./engine --check